# QuickSort - Конфигурация категорий сортировки
# Все материалы должны быть в верхнем регистре (например: STONE, DIAMOND_SWORD)

categories:
  tools:
    - BUCKET
    - WATER_BUCKET
    - LAVA_BUCKET
    - MILK_BUCKET
    - POWDER_SNOW_BUCKET
    - AXOLOTL_BUCKET
    - TROPICAL_FISH_BUCKET
    - SALMON_BUCKET
    - COD_BUCKET
    - PUFFERFISH_BUCKET
    - BRUSH
    - NAME_TAG
    - LEAD
    - BUNDLE
    - SADDLE
    - FIREWORK_ROCKET
    - GOAT_HORN
    - COMPASS
    - RECOVERY_COMPASS
    - CLOCK
    - SPYGLASS
    - OAK_BOAT
    - SPRUCE_BOAT
    - BIRCH_BOAT
    - JUNGLE_BOAT
    - ACACIA_BOAT
    - DARK_OAK_BOAT
    - MANGROVE_BOAT
    - CHERRY_BOAT
    - BAMBOO_RAFT
    - PALE_OAK_BOAT
    - OAK_CHEST_BOAT
    - SPRUCE_CHEST_BOAT
    - BIRCH_CHEST_BOAT
    - JUNGLE_CHEST_BOAT
    - ACACIA_CHEST_BOAT
    - DARK_OAK_CHEST_BOAT
    - MANGROVE_CHEST_BOAT
    - CHERRY_CHEST_BOAT
    - BAMBOO_CHEST_RAFT
    - PALE_OAK_CHEST_BOAT
    - WOODEN_PICKAXE
    - WOODEN_AXE
    - WOODEN_SHOVEL
    - WOODEN_HOE
    - STONE_PICKAXE
    - STONE_AXE
    - STONE_SHOVEL
    - STONE_HOE
    - IRON_PICKAXE
    - IRON_AXE
    - IRON_SHOVEL
    - IRON_HOE
    - GOLDEN_PICKAXE
    - GOLDEN_AXE
    - GOLDEN_SHOVEL
    - GOLDEN_HOE
    - DIAMOND_PICKAXE
    - DIAMOND_AXE
    - DIAMOND_SHOVEL
    - DIAMOND_HOE
    - NETHERITE_PICKAXE
    - NETHERITE_AXE
    - NETHERITE_SHOVEL
    - NETHERITE_HOE
    - SHEARS
    - FLINT_AND_STEEL
    - FISHING_ROD

  weapons:
    - ARROW
    - TIPPED_ARROW
    - SPECTRAL_ARROW
    - WIND_CHARGE
    - SHIELD
    - WOODEN_SWORD
    - STONE_SWORD
    - IRON_SWORD
    - GOLDEN_SWORD
    - DIAMOND_SWORD
    - NETHERITE_SWORD
    - BOW
    - CROSSBOW
    - MACE
    - TRIDENT
    - TOTEM_OF_UNDYING

  armor:
    - LEATHER_HORSE_ARMOR
    - IRON_HORSE_ARMOR
    - GOLDEN_HORSE_ARMOR
    - DIAMOND_HORSE_ARMOR
    - WOLF_ARMOR
    - TURTLE_HELMET
    - LEATHER_HELMET
    - LEATHER_CHESTPLATE
    - LEATHER_LEGGINGS
    - LEATHER_BOOTS
    - CHAINMAIL_HELMET
    - CHAINMAIL_CHESTPLATE
    - CHAINMAIL_LEGGINGS
    - CHAINMAIL_BOOTS
    - IRON_HELMET
    - IRON_CHESTPLATE
    - IRON_LEGGINGS
    - IRON_BOOTS
    - GOLDEN_HELMET
    - GOLDEN_CHESTPLATE
    - GOLDEN_LEGGINGS
    - GOLDEN_BOOTS
    - DIAMOND_HELMET
    - DIAMOND_CHESTPLATE
    - DIAMOND_LEGGINGS
    - DIAMOND_BOOTS
    - NETHERITE_HELMET
    - NETHERITE_CHESTPLATE
    - NETHERITE_LEGGINGS
    - NETHERITE_BOOTS
    - ELYTRA

  ores:
    - LEATHER
    - SHULKER_SHELL
    - NETHER_QUARTZ_ORE
    - QUARTZ
    - REDSTONE_ORE
    - DEEPSLATE_REDSTONE_ORE
    - REDSTONE
    - REDSTONE_BLOCK
    - LAPIS_ORE
    - DEEPSLATE_LAPIS_ORE
    - LAPIS_LAZULI
    - LAPIS_BLOCK
    - COAL_ORE
    - DEEPSLATE_COAL_ORE
    - CHARCOAL
    - COAL
    - COAL_BLOCK
    - COPPER_ORE
    - DEEPSLATE_COPPER_ORE
    - RAW_COPPER
    - COPPER_INGOT
    - COPPER_BLOCK
    - IRON_ORE
    - DEEPSLATE_IRON_ORE
    - RAW_IRON
    - IRON_NUGGET
    - IRON_INGOT
    - IRON_BLOCK
    - GOLD_ORE
    - DEEPSLATE_GOLD_ORE
    - NETHER_GOLD_ORE
    - RAW_GOLD
    - GOLD_NUGGET
    - GOLD_INGOT
    - GOLD_BLOCK
    - DIAMOND_ORE
    - DEEPSLATE_DIAMOND_ORE
    - DIAMOND
    - DIAMOND_BLOCK
    - EMERALD_ORE
    - DEEPSLATE_EMERALD_ORE
    - EMERALD
    - EMERALD_BLOCK
    - ANCIENT_DEBRIS
    - NETHERITE_SCRAP
    - NETHERITE_INGOT
    - NETHERITE_BLOCK

  food:
    - PUFFERFISH
    - SPIDER_EYE
    - POISONOUS_POTATO
    - ROTTEN_FLESH
    - DRIED_KELP
    - TROPICAL_FISH
    - POTATO
    - BEETROOT
    - CHICKEN
    - MELON_SLICE
    - SWEET_BERRIES
    - GLOW_BERRIES
    - COOKIE
    - COD
    - SALMON
    - MUTTON
    - RABBIT
    - BEEF
    - CARROT
    - PORKCHOP
    - APPLE
    - BREAD
    - BAKED_POTATO
    - COOKED_COD
    - COOKED_RABBIT
    - COOKED_SALMON
    - COOKED_CHICKEN
    - COOKED_MUTTON
    - MUSHROOM_STEW
    - BEETROOT_SOUP
    - SUSPICIOUS_STEW
    - PUMPKIN_PIE
    - COOKED_PORKCHOP
    - COOKED_BEEF
    - RABBIT_STEW
    - CAKE
    - HONEY_BOTTLE
    - CHORUS_FRUIT
    - GOLDEN_CARROT
    - GOLDEN_APPLE
    - ENCHANTED_GOLDEN_APPLE

  blocks:
    - STONE
    - DIORITE
    - GRANITE
    - ANDESITE
    - COBBLESTONE
    - SMOOTH_STONE
    - DIRT
    - GRASS_BLOCK
    - COARSE_DIRT
    - PODZOL
    - MYCELIUM
    - SAND
    - RED_SAND
    - GRAVEL
    - SANDSTONE
    - CUT_SANDSTONE
    - CHISELED_SANDSTONE
    - SNOW_BLOCK
    - ICE
    - PACKED_ICE
    - BLUE_ICE
    - CLAY
    - STONE_BRICKS
    - CRACKED_STONE_BRICKS
    - MOSSY_STONE_BRICKS
    - CHISELED_STONE_BRICKS
    - BRICKS
    - OBSIDIAN
    - NETHERRACK
    - SOUL_SAND
    - SOUL_SOIL
    - BASALT
    - POLISHED_BASALT
    - BLACKSTONE
    - POLISHED_BLACKSTONE
    - POLISHED_BLACKSTONE_BRICKS
    - CRACKED_POLISHED_BLACKSTONE_BRICKS
    - CHISELED_POLISHED_BLACKSTONE
    - END_STONE

  decor:
    - CRAFTING_TABLE
    - LADDER
    - OAK_FENCE
    - SPRUCE_FENCE
    - BIRCH_FENCE
    - JUNGLE_FENCE
    - ACACIA_FENCE
    - DARK_OAK_FENCE
    - MANGROVE_FENCE
    - CHERRY_FENCE
    - BAMBOO_FENCE
    - CRIMSON_FENCE
    - WARPED_FENCE
    - OAK_FENCE_GATE
    - SPRUCE_FENCE_GATE
    - BIRCH_FENCE_GATE
    - JUNGLE_FENCE_GATE
    - ACACIA_FENCE_GATE
    - DARK_OAK_FENCE_GATE
    - MANGROVE_FENCE_GATE
    - CHERRY_FENCE_GATE
    - BAMBOO_FENCE_GATE
    - CRIMSON_FENCE_GATE
    - WARPED_FENCE_GATE
    - OAK_STAIRS
    - SPRUCE_STAIRS
    - BIRCH_STAIRS
    - JUNGLE_STAIRS
    - ACACIA_STAIRS
    - DARK_OAK_STAIRS
    - MANGROVE_STAIRS
    - CHERRY_STAIRS
    - BAMBOO_STAIRS
    - CRIMSON_STAIRS
    - WARPED_STAIRS
    - STONE_BRICK_STAIRS
    - COBBLESTONE_STAIRS
    - SANDSTONE_STAIRS
    - BRICK_STAIRS
    - NETHER_BRICK_STAIRS
    - POLISHED_BLACKSTONE_STAIRS
    - OAK_SLAB
    - SPRUCE_SLAB
    - BIRCH_SLAB
    - JUNGLE_SLAB
    - ACACIA_SLAB
    - DARK_OAK_SLAB
    - MANGROVE_SLAB
    - CHERRY_SLAB
    - BAMBOO_SLAB
    - CRIMSON_SLAB
    - WARPED_SLAB
    - STONE_BRICK_SLAB
    - COBBLESTONE_SLAB
    - SANDSTONE_SLAB
    - BRICK_SLAB
    - NETHER_BRICK_SLAB
    - POLISHED_BLACKSTONE_SLAB
    - CAMPFIRE
    - SOUL_CAMPFIRE
    - LANTERN
    - SOUL_LANTERN
    - BOOKSHELF
    - BARREL
    - SMOKER
    - BLAST_FURNACE
    - FLETCHING_TABLE
    - LOOM
    - CAULDRON
    - WATER_CAULDRON
    - LAVA_CAULDRON
    - POWDER_SNOW_CAULDRON
    - BELL
    - ITEM_FRAME
    - PAINTING
    - CHEST
    - TRAPPED_CHEST
    - ENDER_CHEST
    - SHULKER_BOX
    - WHITE_SHULKER_BOX
    - ORANGE_SHULKER_BOX
    - MAGENTA_SHULKER_BOX
    - LIGHT_BLUE_SHULKER_BOX
    - YELLOW_SHULKER_BOX
    - LIME_SHULKER_BOX
    - PINK_SHULKER_BOX
    - GRAY_SHULKER_BOX
    - LIGHT_GRAY_SHULKER_BOX
    - CYAN_SHULKER_BOX
    - PURPLE_SHULKER_BOX
    - BLUE_SHULKER_BOX
    - BROWN_SHULKER_BOX
    - GREEN_SHULKER_BOX
    - RED_SHULKER_BOX
    - BLACK_SHULKER_BOX
    - BEACON
    - CANDLE
    - WHITE_CANDLE
    - ORANGE_CANDLE
    - MAGENTA_CANDLE
    - LIGHT_BLUE_CANDLE
    - YELLOW_CANDLE
    - LIME_CANDLE
    - PINK_CANDLE
    - GRAY_CANDLE
    - LIGHT_GRAY_CANDLE
    - CYAN_CANDLE
    - PURPLE_CANDLE
    - BLUE_CANDLE
    - BROWN_CANDLE
    - GREEN_CANDLE
    - RED_CANDLE
    - BLACK_CANDLE
    - POTTED_ACACIA_SAPLING
    - POTTED_BIRCH_SAPLING
    - POTTED_DARK_OAK_SAPLING
    - POTTED_JUNGLE_SAPLING
    - POTTED_OAK_SAPLING
    - POTTED_SPRUCE_SAPLING
    - EXPOSED_COPPER
    - WEATHERED_COPPER
    - OXIDIZED_COPPER
    - CUT_COPPER
    - EXPOSED_CUT_COPPER
    - WEATHERED_CUT_COPPER
    - OXIDIZED_CUT_COPPER
    - CUT_COPPER_SLAB
    - CUT_COPPER_STAIRS
    - OAK_LEAVES
    - SPRUCE_LEAVES
    - BIRCH_LEAVES
    - JUNGLE_LEAVES
    - ACACIA_LEAVES
    - DARK_OAK_LEAVES
    - MANGROVE_LEAVES
    - CHERRY_LEAVES
    - AZALEA_LEAVES
    - FLOWERING_AZALEA_LEAVES
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - MANGROVE_PLANKS
    - CHERRY_PLANKS
    - BAMBOO_PLANKS
    - CRIMSON_PLANKS
    - WARPED_PLANKS
    - OAK_LOG
    - STRIPPED_OAK_LOG
    - OAK_WOOD
    - STRIPPED_OAK_WOOD
    - SPRUCE_LOG
    - STRIPPED_SPRUCE_LOG
    - SPRUCE_WOOD
    - STRIPPED_SPRUCE_WOOD
    - BIRCH_LOG
    - STRIPPED_BIRCH_LOG
    - BIRCH_WOOD
    - STRIPPED_BIRCH_WOOD
    - JUNGLE_LOG
    - STRIPPED_JUNGLE_LOG
    - JUNGLE_WOOD
    - STRIPPED_JUNGLE_WOOD
    - ACACIA_LOG
    - STRIPPED_ACACIA_LOG
    - ACACIA_WOOD
    - STRIPPED_ACACIA_WOOD
    - DARK_OAK_LOG
    - STRIPPED_DARK_OAK_LOG
    - DARK_OAK_WOOD
    - STRIPPED_DARK_OAK_WOOD
    - MANGROVE_LOG
    - STRIPPED_MANGROVE_LOG
    - MANGROVE_WOOD
    - STRIPPED_MANGROVE_WOOD
    - CHERRY_LOG
    - STRIPPED_CHERRY_LOG
    - CHERRY_WOOD
    - STRIPPED_CHERRY_WOOD
    - BAMBOO_BLOCK
    - STRIPPED_BAMBOO_BLOCK
    - CRIMSON_STEM
    - STRIPPED_CRIMSON_STEM
    - CRIMSON_HYPHAE
    - STRIPPED_CRIMSON_HYPHAE
    - WARPED_STEM
    - STRIPPED_WARPED_STEM
    - WARPED_HYPHAE
    - STRIPPED_WARPED_HYPHAE
    - PALE_OAK_LOG
    - STRIPPED_PALE_OAK_LOG
    - PALE_OAK_WOOD
    - STRIPPED_PALE_OAK_WOOD
    - GLASS
    - WHITE_STAINED_GLASS
    - ORANGE_STAINED_GLASS
    - MAGENTA_STAINED_GLASS
    - LIGHT_BLUE_STAINED_GLASS
    - YELLOW_STAINED_GLASS
    - LIME_STAINED_GLASS
    - PINK_STAINED_GLASS
    - GRAY_STAINED_GLASS
    - LIGHT_GRAY_STAINED_GLASS
    - CYAN_STAINED_GLASS
    - PURPLE_STAINED_GLASS
    - BLUE_STAINED_GLASS
    - BROWN_STAINED_GLASS
    - GREEN_STAINED_GLASS
    - RED_STAINED_GLASS
    - BLACK_STAINED_GLASS
    - SKELETON_SKULL
    - CREEPER_HEAD
    - PIGLIN_HEAD
    - ZOMBIE_HEAD
    - WITHER_SKELETON_SKULL
    - DRAGON_HEAD
    - PLAYER_HEAD

  redstone:
    - REDSTONE_TORCH
    - REDSTONE_BLOCK
    - REPEATER
    - COMPARATOR
    - PISTON
    - STICKY_PISTON
    - OBSERVER
    - HOPPER
    - DROPPER
    - DISPENSER
    - NOTE_BLOCK
    - LEVER
    - STONE_BUTTON
    - OAK_BUTTON
    - SPRUCE_BUTTON
    - BIRCH_BUTTON
    - JUNGLE_BUTTON
    - ACACIA_BUTTON
    - DARK_OAK_BUTTON
    - MANGROVE_BUTTON
    - CHERRY_BUTTON
    - BAMBOO_BUTTON
    - CRIMSON_BUTTON
    - WARPED_BUTTON
    - POLISHED_BLACKSTONE_BUTTON
    - STONE_PRESSURE_PLATE
    - OAK_PRESSURE_PLATE
    - SPRUCE_PRESSURE_PLATE
    - BIRCH_PRESSURE_PLATE
    - JUNGLE_PRESSURE_PLATE
    - ACACIA_PRESSURE_PLATE
    - DARK_OAK_PRESSURE_PLATE
    - MANGROVE_PRESSURE_PLATE
    - CHERRY_PRESSURE_PLATE
    - BAMBOO_PRESSURE_PLATE
    - CRIMSON_PRESSURE_PLATE
    - WARPED_PRESSURE_PLATE
    - LIGHT_WEIGHTED_PRESSURE_PLATE
    - HEAVY_WEIGHTED_PRESSURE_PLATE
    - TRIPWIRE_HOOK
    - TRIPWIRE
    - TARGET
    - DAYLIGHT_DETECTOR
    - SCULK_SENSOR
    - RAIL
    - POWERED_RAIL
    - DETECTOR_RAIL
    - ACTIVATOR_RAIL

  brewing:
    - BREWING_STAND
    - BLAZE_ROD
    - BLAZE_POWDER
    - NETHER_WART
    - GLASS_BOTTLE
    - FERMENTED_SPIDER_EYE
    - GLISTERING_MELON_SLICE
    - MAGMA_CREAM
    - SUGAR
    - RABBIT_FOOT
    - PHANTOM_MEMBRANE
    - GLOWSTONE_DUST
    - GUNPOWDER
    - DRAGON_BREATH

  farming:
    - WHEAT_SEEDS
    - WHEAT
    - HAY_BLOCK
    - BEETROOT_SEEDS
    - MELON_SEEDS
    - MELON
    - PUMPKIN_SEEDS
    - PUMPKIN
    - SUGAR_CANE
    - CACTUS
    - KELP
    - BONE
    - BONE_MEAL
    - EGG
    - BROWN_EGG
    - BLUE_EGG
    - FEATHER

  enchanted_books:
    - BOOK
    - ENCHANTED_BOOK

  potions:
    - POTION
    - SPLASH_POTION
    - LINGERING_POTION
    - OMINOUS_BOTTLE
    - EXPERIENCE_BOTTLE
